name: V3 tests
on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  trigger_sai-gh:
    name: Run fb-e2e-suite Reusable Workflow
    uses: saikumar-vs/pmm-qa/.github/workflows/fb-e2e-suite.yml@sai-gh
    secrets: inherit
    with:
      sha: ${{ 'null' }}
      pmm_server_image: ${{ 'perconalab/pmm-server:dev-latest' }}
      pmm_client_version: ${{ 'dev-latest' }}
      pmm_client_image: ${{ 'perconalab/pmm-client:dev-latest' }}
      pmm_qa_branch: ${{ 'v3' }}
      pmm_ui_tests_branch: ${{ 'v3' }}